// ============================================================================
//  Generative Hours — English control labels (buttons & sliders in artworks).
//  ctrlLabel() in i18n.js maps the exact Korean source string to this table.
// ============================================================================

export const CTRL_EN = {
  "DENSITY 밀도": "DENSITY",
  "DISPERSION 분광": "DISPERSION",
  "GLITCH 글리치": "GLITCH",
  "MIST (안개 회복)": "MIST",
  "OUTLINE — 다리 없이": "OUTLINE",
  "RADIANCE 광채": "RADIANCE",
  "RAIN SPEED 강우": "RAIN SPEED",
  "RAYS 틈": "RAYS",
  "REVEAL 형상": "REVEAL",
  "개 모두 회수 (recall dogs)": "Recall Dogs",
  "갤러리": "Gallery",
  "거울": "Mirror",
  "거울 대칭": "Mirror Symmetry",
  "고스트 (Ghost)": "Ghost",
  "굴 키우기 (dig)": "Dig",
  "궤적 TRAIL": "TRAIL",
  "글자 바꾸기 (next glyph)": "Next Glyph",
  "기다림 비우기": "Clear Waiting",
  "기록 초기화": "Reset Records",
  "깊이/조명 (depth)": "Depth",
  "깜빡임 (blink)": "Blink",
  "눈 (snow)": "Snow",
  "다시": "Again",
  "다시 깨기 (Reshatter)": "Reshatter",
  "다시 심기 (Replant)": "Replant",
  "다시 적응": "Re-adapt",
  "다음 시행": "Next Trial",
  "돌풍 (Gust)": "Gust",
  "드로우": "Draw",
  "마법의 각도로": "Magic Angle",
  "막대기 (rod)": "Rod",
  "만화경": "Kaleidoscope",
  "먹이 추가 (add food)": "Add Food",
  "모이기 (assemble)": "Assemble",
  "무작위": "Random",
  "무작위 주파수 (random mode)": "Random Mode",
  "물빛 (shimmer)": "Shimmer",
  "물살": "Current",
  "물살 (flow)": "Flow",
  "뮐러-라이어": "Müller-Lyer",
  "반반 (reset)": "Reset",
  "반전 (헤르만 격자)": "Invert (Hermann)",
  "방사형 (Radial)": "Radial",
  "배치 리셋": "Reset Layout",
  "벽 재배치 (reset walls)": "Reset Walls",
  "비우기": "Clear",
  "비우기 (Clear)": "Clear",
  "비우기 (clear)": "Clear",
  "비움 (clear — empty the scroll)": "Clear",
  "빙렬 밀도 (crackle)": "Crackle",
  "새 곡선 (new curve)": "New Curve",
  "새 성좌 (new graph)": "New Graph",
  "새김 굵기 (line)": "Line",
  "속도 SPEED": "SPEED",
  "쏟기 (dump)": "Dump",
  "씨앗 (Reseed)": "Reseed",
  "씨앗 뿌리기": "Sow Seeds",
  "약속 — 지금 + 5분": "Promise +5 min",
  "양 풀어주기 (release sheep)": "Release Sheep",
  "원기둥 제자리": "Reset Cylinder",
  "으르렁 반경 (growl)": "Growl",
  "응집 (condense all)": "Condense All",
  "익살 (exaggeration)": "Exaggeration",
  "자동 (auto)": "Auto",
  "자동 탐색": "Auto Explore",
  "자동 회전": "Auto Rotate",
  "자유": "Free",
  "잔잔하게 (Calm)": "Calm",
  "잔잔하게 (calm)": "Calm",
  "재배치 (re-seed)": "Re-seed",
  "재생성": "Regenerate",
  "재생성 (Regenerate)": "Regenerate",
  "재생성 (Reset)": "Reset",
  "저녁 (dusk)": "Dusk",
  "전부 남자 옷": "All Male Pattern",
  "전부 여자 옷": "All Female Pattern",
  "절규 (the scream)": "The Scream",
  "점프 (jump)": "Jump",
  "정렬 (grid)": "Grid",
  "정렬 (re-arrange)": "Re-arrange",
  "제자리로": "Return",
  "중력 GRAVITY": "GRAVITY",
  "지금 테스트": "Test Now",
  "지우기 (clear)": "Clear",
  "직선 (Linear)": "Linear",
  "진입 (dive in)": "Dive In",
  "초기화 (reset deformation)": "Reset Shape",
  "초기화 (reset)": "Reset",
  "침묵 (silence)": "Silence",
  "크게 출렁 (surge)": "Surge",
  "크기": "Size",
  "태양계 (reset)": "Reset",
  "판정": "Check",
  "폰조 (기찻길)": "Ponzo (Rails)",
  "풍선 크기": "Balloon Size",
  "함성 (roar)": "Roar",
  "황금각 (137.5°)": "Golden 137.5°",
  "회전": "Rotate",
  "흔들림 (sway)": "Sway",
  "흩기 (Reset)": "Reset",
  "흩기 (scatter all)": "Scatter All",
  "흩어지기 (scatter)": "Scatter",
  "힘 (force)": "Force",
};
